development: &defaults
  chef_node_name: bentobox
  chef_client_key: config/bentobox.pem
  chef_server_api_url: http://vagrant.namics.com:4000
  chef_server_admin_url: http://vagrant.namics.com:4040

  #chef_environment: _default
  #chef_cookbook_all_versions: false

test:
  chef_node_name: bentobox
  chef_client_key: config/test.pem
  chef_server_api_url: http://localhost:4000
  chef_server_admin_url: http://localhost:4040

production:
  <<: *defaults

