development: &defaults
  node_name: test
  client_key: config/test.pem
  chef_server_url: http://localhost:4000
  #environment: _default
  all_versions: false

test:
  <<: *defaults

production:
  <<: *defaults
