development: &defaults
  chef_node_name: bentobox
  chef_client_key: config/bentobox.pem
  chef_server_api_url: http://vagrant.namics.com:4000
  chef_server_admin_url: http://vagrant.namics.com:4040

  #chef_environment: _default
  #chef_cookbook_all_versions: false

test:
  #supply a list of cookbooks as alternative to a chef server
  cookbooks: apache2, mysql, third

production:
  chef_node_name: bentobox
  chef_client_key: config/bentobox.pem
  chef_server_api_url: http://vagrant.namics.com:4000
  chef_server_admin_url: http://vagrant.namics.com:4040

