development: &defaults
  chef_node_name: test
  chef_client_key: config/test.pem
  chef_server_url: http://localhost:4000
  #chef_environment: _default
  #chef_cookbook_all_versions: false

test:
  #supply a list of cookbooks as alternative to a chef server
  cookbooks: apache2, mysql, third

production:
  chef_node_name: bentobox
  chef_client_key: config/bentobox.pem
  chef_server_url: http://localhost:4000

