development: &defaults
  chef_node_name: test
  chef_client_key: config/test.pem
  chef_server_url: http://localhost:4000
  #chef_environment: _default
  #chef_cookbook_all_versions: false


test:
  cookbooks: apache2, mysql, third

production:
  #only supplied because the heroku demo doesn't have a chef-server attached
  cookbooks: apache2, mysql, third
