development: &defaults
  chef:
    node_name: test
    client_key: config/test.pem
    chef_server_url: http://localhost:4000
    #environment: _default
    all_versions: false
    cookbooks: apache2, mysql, another one,

test:
  <<: *defaults
  chef:
    cookbooks: apache2, mysql, third

production:
  <<: *defaults
