development: &defaults
  chef:
    node_name: test
    client_key: config/test.pem
    #chef_server_url: http://localhost:4000
    #environment: _default
    #all_versions: false


test:
  chef:
    cookbooks: apache2, mysql, third

production:
  chef:
    #only supplied because the heroku demo doesn't have a chef-server attached
    cookbooks: apache2, mysql, third
