defaults: &defaults
  allow_dynamic_fields: true
  parameterize_keys: true
  persist_in_safe_mode: true
  raise_not_found_error: true
  reconnect_time: 3
  use_object_ids: true


development:
  <<: *defaults
  sessions:
    default: &default_session
      database: vagrant_cook_development
      hosts:
        - localhost:27017
      options:
        consistency: :strong

test:
  <<: *defaults
  sessions:
    default:
      <<: *default_session
      database: vagrant_cook_test


<% if ENV['MONGOHQ_URL'] %>
  <% uri = URI.parse(ENV['MONGOHQ_URL']) %>
production:
  <<: *defaults
  sessions:
    default:
      <<: *default_session
      database: <%= uri.path.sub('/','') %>
      username: <%= uri.user %>
      password: <%= uri.password %>
      hosts:
        - <%= uri.host %>:<%= uri.port %>
<% end %>