development: &defaults
  sessions:
    default: &default_session
      database: vagrant_cook_development
      hosts:
        - localhost:27017
      options:
        consistency: :strong
        allow_dynamic_fields: true
        autocreate_indexes: true
        parameterize_keys: true
        persist_in_safe_mode: true
        raise_not_found_error: true
        reconnect_time: 3
        use_object_ids: true

test:
  <<: *defaults
  sessions:
    default:
      <<: *default_session
      database: vagrant_cook_test

# for heroku environment
production:
  <<: *defaults
  sessions:
    default:
      <<: *default_session
      database: app5790333
      username: heroku
      password: 820d543aac57c58b7813e605126d047d
      hosts:
        - flame.mongohq.com:27108

