development:
  sessions:
    default:
      database: vagrant_cook_development
      hosts:
        - localhost:27017
      options:
        consistency: :strong

test:
  sessions:
    default:
      database: vagrant_cook_test
      hosts:
        - localhost:27017
      options:
        consistency: :strong
