development: &defaults
  sessions:
    default: &default_session
      database: bentobox_development
      hosts:
        - localhost:27017
      options:
        consistency: :strong
        allow_dynamic_fields: true
        autocreate_indexes: true
        parameterize_keys: true
        persist_in_safe_mode: true
        raise_not_found_error: true
        reconnect_time: 3
        use_object_ids: true

test:
  <<: *defaults
  sessions:
    default:
      <<: *default_session
      database: bentobox_text

# for heroku environment
<% if ENV['MONGOHQ_URL'] %>
  <% uri = URI.parse(ENV['MONGOHQ_URL']) %>
production:
  <<: *defaults
  sessions:
    default:
      <<: *default_session
      database: <%= uri.path.sub('/','') %>
      username: <%= uri.users %>
      password: <%= uri.password %>
      hosts:
        - <%= uri.host %>:<%= uri.port %>
<% else %>
production:
  <<: *defaults
  sessions:
    default:
      <<: *default_session
      database: bentobox_production
<% end %>