defaults: &defaults
  allow_dynamic_fields: true
  parameterize_keys: true
  persist_in_safe_mode: true
  raise_not_found_error: true
  reconnect_time: 3
  use_object_ids: true


development:
  <<: *defaults
  sessions:
    default:
      database: vagrant_cook_development
      hosts:
        - localhost:27017
      options:
        consistency: :strong

test:
  <<: *defaults
  sessions:
    default:
      database: vagrant_cook_test
      hosts:
        - localhost:27017
      options:
        consistency: :strong

production:
  <<: *defaults
  uri: <%= ENV['MONGOHQ_URL'] %>
